### ISSUE TITLE
Update extension for Gnome 3.18

### ISSUE THREAD

**Issue by ConorIA** [MK-42/deskcon-desktop#5]
Great on you for carrying on with the Deskcon legacy. Your fork is currently being used to populate the AUR deskcon-desktop-git package (https://aur.archlinux.org/packages/deskcon-desktop-git/). Unfortunately, Gnome 3.18 has broken the deskcon extension.

**Comment by MK-42** [comment]
I haven't used this for some time. It is not completly working and i am still bugfixing but ive committed some changes to make it work at all.
If I find time I'll update this and the android app again to make everything working again. Some types of notifications aren't working and file-transfer is buggy.
But 3.18 works now.
